name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: the name of the deployable artifact files
        required: true 
        default: dist 
        type: string
    outputs:
      result:
        description: the result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:    
  # outputs:
  # ko để outputs ở đây, vì cái output đang muốn sinh ra nằm trong job deploy, nên phải
  # cho outputs nested bên trong job deploy
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: output information
        run: echo "Deploying and uploading..." 
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT